// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgsrzqUFOv5azJEE1JJzI4ZNh7ml9RHc',
    appId: '1:172304756434:web:b73f2cabb02a344b52870b',
    messagingSenderId: '172304756434',
    projectId: 'supply2trade-48690',
    authDomain: 'supply2trade-48690.firebaseapp.com',
    storageBucket: 'supply2trade-48690.firebasestorage.app',
    measurementId: 'G-MRR3LKQTN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7r6UrwOeshBB20_E2eh4fg6z4YxGd8E0',
    appId: '1:172304756434:android:6e590bf88387bf0052870b',
    messagingSenderId: '172304756434',
    projectId: 'supply2trade-48690',
    storageBucket: 'supply2trade-48690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV0Qvpsb_ZXgIDdrgiaHzxtJwQLo2fG-g',
    appId: '1:172304756434:ios:698ebd569e00da5a52870b',
    messagingSenderId: '172304756434',
    projectId: 'supply2trade-48690',
    storageBucket: 'supply2trade-48690.firebasestorage.app',
    iosBundleId: 'com.example.supplyToTrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV0Qvpsb_ZXgIDdrgiaHzxtJwQLo2fG-g',
    appId: '1:172304756434:ios:698ebd569e00da5a52870b',
    messagingSenderId: '172304756434',
    projectId: 'supply2trade-48690',
    storageBucket: 'supply2trade-48690.firebasestorage.app',
    iosBundleId: 'com.example.supplyToTrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgsrzqUFOv5azJEE1JJzI4ZNh7ml9RHc',
    appId: '1:172304756434:web:04f43decf63ec25452870b',
    messagingSenderId: '172304756434',
    projectId: 'supply2trade-48690',
    authDomain: 'supply2trade-48690.firebaseapp.com',
    storageBucket: 'supply2trade-48690.firebasestorage.app',
    measurementId: 'G-LGL2KPBT5G',
  );
}
